name: CI

on:
  push:
    branches: [ main, feature/lydia-specs ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql

      - name: Show PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --ignore-platform-reqs -vvv

      - name: Validate Symfony config
        run: php bin/console lint:yaml config/ --no-interaction

      - name: Check database migrations status
        run: php bin/console doctrine:migrations:status --quiet

      # Si on ajoute des tests PHPUnit, d√©commentez ces lignes :
      #- name: Run tests
      #  run: php bin/phpunit
